name: Close PR

on:
  pull_request:
    types:
      - closed

jobs:
  send-pr-number-to-clean:
    name: Record PR number to clean ğŸ“¤
    runs-on: ubuntu-latest
    steps:
      - name: Upload PR number ğŸ“¤
        uses: sliit-foss/actions/preview-deployments/upload-pr-number@main
